### ISSUE TITLE
Traduction de Pull Request qui conserve l’acronyme

### ISSUE THREAD

**Issue by progval** [soulaklabs/bitoduc.fr#100]
Je vois souvent l’utilisation de « PR », même dans des discussions en français.
Est-ce qu’on ne pourrait pas trouvrer une autre traduction à « Pull Request » qui conserve cet acronyme ?

Par exemple : Postulation à une Réconciliation.
Éventuellement raccourci en Posturéconciliation, ou semblable.

**Comment by chmduquesne** [comment]
Nous en avons déjà discuté dans #97: personnellement j'aime beaucoup « Fusiodemande » et je serais très triste si nous perdions cette traduction. Quel est l'intérêt de se plier au diktat de la langue anglaise, en voulant créer une traduction spécifiquement de façon à copier l'acronmyme? Pouvoir dire PR, pour faire comme les anglais... Est-ce vraiment un noble but?

**Comment by progval** [comment]
J’aime aussi beaucoup Fusiodemande, mais c’était (une fois de plus) pour essayer de chercher encore mieux

**Comment by chmduquesne** [comment]
Je sais! Ce gestionnaire de bogue est le lieu des discussions pédantes et des décisions unilatérales de notre maître à penser @p0nce. J'ai exposé mon point de vue et j'apprécie par ailleurs ton effort pour l'amélioration continue. J'espère simplement que l'indécision qui caractérise ce projet va l'emporter et qu'on va garder l'actuelle traduction. Il faut perpétuer cette esprit « Académie française » que nous avons acquis!

**Comment by p0nce** [comment]
Dans un idéal de justesse - voire de justice - il nous faut considérer tout sérieusement la forme inversée « RP »

On se souvient en effet de « UE » et "EU" , de « TVA » et "VAT" et encore de « CIO » et son cousin "IOC".

Nous vivons certes dans un monde de compromis. Or il est déjà plus ou moins la norme de mélanger les lettres des acronymes en français par rapport à leurs équivalents impérialistes.

**Comment by TaTaaaa** [comment]
Je propose "requête de pardessus", RP.

Bien à vous, les garçons.
