### ISSUE TITLE
Nous n'avons plus d'analyse de traffic

### ISSUE THREAD

**Issue by p0nce** [soulaklabs/bitoduc.fr#107]
Sur le dernier mois, Google rapporte un compte total de 97 visiteurs, dont 100% serait du pourriel de "Referrer" (vous savez, les faux visiteurs utilisés par les arroseurs publicitaires). C'est beaucoup moins que les 600 uniques / mois environ qu'on avait avant.
Je pense que le patron de code fourni par Google a été cassé lors de sa réécriture. Mais je ne veux pas jeter la pierre sur @chmduquesne , tout le monde est concerné !

**Comment by chmduquesne** [comment]
Je ne nie pas la possibilité que ça soit de ma faute, mais investiguer ceci
ne me motive pas vraiment et je n'ai pas le temps de m'y consacrer pour
l'instant.

Comme tu es le seul à pouvoir utiliser les statistiques de gogol analytics,
à toi de voir si tu veux passer du temps dessus :D

**Comment by p0nce** [comment]
On a qu'à les enlever, vu que je ne les regarde pas non plus. Tout le monde s'en contrefiche !

**Comment by p0nce** [comment]
Et voilà ! 9d37ffa50ea3e3ed3cf551d25237e9e1010f5ff1
