### ISSUE TITLE
Air Gap

### ISSUE THREAD

**Issue by maaaaz** [soulaklabs/bitoduc.fr#108]
Je propose "physolation", ou "phisolation" :)

**Comment by p0nce** [comment]
On fonctionne par fusio-demande. Sans atome de code, pas d'évolution.

**Comment by ProgVal** [comment]
On peut quand même en discuter sur un ticket avant de créer une fusiodemande.

**Comment by maaaaz** [comment]
Entendu, la fusio arrive.

**Comment by chmduquesne** [comment]
Fermé car vieux.
