### ISSUE TITLE
Propositions de traductions

### ISSUE THREAD

**Issue by mynameisv** [soulaklabs/bitoduc.fr#110]
Bonjour,
Voici quelques propositions de traductions :
-  attaque par brute force -> attaques exhaustive 
-  salt -> diversificateur
- ASLR : "Distribution" Stochastique de l’espace d’adressage
- Man-in-the-middle attack : attaque du singe intercepteur

Bien sûr ce ne sont que des propositions :-)
Bonne journée.

**Comment by p0nce** [comment]
Bonjour, je vous explique la marche à suivre.
1. Vous devez établir une fusio-demande
2. Une discussion pédante à lieu
3. Soit la fusio-demande est fusionnée, soit non, soit plus probablement il ne se passe rien du tout.

Bien à vous et excellent Lundi.

**Comment by mynameisv** [comment]
Bonjour, merci pour les indications. Je me disais aussi que c'était trop simple de "juste" poster mes propositions ;-).
Je "fusio-demande" et nous verrons.
Bonne journée.

**Comment by chmduquesne** [comment]
Il me semble que ces traductions ont toutes été traitées. Merci d'ouvrir un seul ticket par traduction s'il en manque toujours.
