### ISSUE TITLE
Ajout Blockchain

### ISSUE THREAD

**Issue by slashbinslashnoname** [soulaklabs/bitoduc.fr#111]
Blockchain : Nom Féminin :  Chaîne de bloc

**Comment by progval** [comment]
plutôt « chaine de blocs », non ?

**Comment by ghost** [comment]
Stéphane Bortzmeyer a présenté une conférence au FIC 2017, intitulée « Gouvernance de la chaîne de blocs ». Ça confirmerait ta proposition :-)

**Comment by slashbinslashnoname** [comment]
my bad

**Comment by chmduquesne** [comment]
Vous êtes invité à créer un atome de code correspondant à votre proposition!

**Comment by ghost** [comment]
Réglé dans #123 (nous irons au bois).
