### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by flarcher** [soulaklabs/bitoduc.fr#128]
Bonjour,

Je n'ai pas trouvé _Connection pool_ alors je suggère de l'ajouter
Que penseriez vous de _Réserve de connexions_ ?

**Comment by martinkirch** [comment]
Bonjour,
Je propose qu'on élargisse a _pool_, puisqu'il existe aussi _thread pool_ ou _object pool_ .  Vu le thème du site, pas besoin de préciser qu'il ne s'agit pas de piscines...

(relevant avec stupeur qu'il manque _thread_ dans notre collection, j'en profite pour ouvrir #129)

**Comment by chmduquesne** [comment]
Réserve => 👍
