### ISSUE TITLE
What The Fuck

### ISSUE THREAD

**Issue by chmduquesne** [soulaklabs/bitoduc.fr#132]
Abbrégé par "WTF".

Proposition: _CQCB_ pour _C'est Quoi Ce Bordel_.

**Comment by ghost** [comment]
C'est _The_, pas _This_, j'aurai donc plutôt proposé _C'est Quoi Le Bordel_.

**Comment by flarcher** [comment]
Mon humble opinion serait que *C'est Quoi Ce Bordel* décrit mieux la situation.
La traduction strictement littérale *C'est Quoi Le Bordel* me semble inutilisée (et peut être même dénuée de sens, en français du moins).

Je vote pour *C'est Quoi Ce Bordel* :+1:

**Comment by martinkirch** [comment]
C'est vrai que cette expression revient souvent dans l'informatique, mais elle est beaucoup plus générale !
Est-ce vraiment du ressort d'"un site pour la promotion de la francophonie dans le monde informatique", si vous me permettez de paraphraser `LISEZMOI.md` ?

**Comment by feth** [comment]
Portnawak ?

Par ailleurs, citation wikipedia: «En mars 2009 , la WTFPL version 2 est traduite en français par Samuel Hocevar, sous le nom de Licence Publique Rien À Branler (LPRAB)»

**Comment by chmduquesne** [comment]
Fermé car vieux et pas spécifique à l'informatique.
