### ISSUE TITLE
Champ de recherche

### ISSUE THREAD

**Issue by lenormf** [soulaklabs/bitoduc.fr#136]
Salut,

Ce serait pratique de pouvoir avoir une traduction instantannée grâce à un champ en haut de la page, pour éviter d'avoir à lire une liste.

Merci.

**Comment by progval** [comment]
Quel avantage cela aurait-il par rapport à Ctrl-f ?

**Comment by p0nce** [comment]
N'est-ce pas en contradiction avec #137 ?

**Comment by chmduquesne** [comment]
Cette proposition n'ayant pas réussi à faire l'unanimité et n'étant pas accompagnée d'une FD, je me vois contraint de la fermer.
