### ISSUE TITLE
Le picorage avec git

### ISSUE THREAD

**Issue by flarcher** [soulaklabs/bitoduc.fr#138]
Voici un message d'aide de *git* dans le cas d'un conflit lors du *cherry-pick*
```
Votre branche est à jour avec 'origin/master'.
Vous êtes actuellement en train de picorer le commit 75a0583.
  (réglez les conflits puis lancez "git cherry-pick --continue")
  (utilisez "git cherry-pick --abort" pour annuler le picorage)
```

J'aime bien cette traduction de *cherry-pick* en *picorage* :smile: 
A ajouter ?

**Comment by p0nce** [comment]
Tout à fait, on attend impatiemment votre FD.

**Comment by p0nce** [comment]
On attends votre FD avec impatience.

**Comment by flarcher** [comment]
J'ai soumis [la fusiodemande correspondante](https://github.com/soulaklabs/bitoduc.fr/pull/141).

**Comment by p0nce** [comment]
C'est maintenant fusionné.
