### ISSUE TITLE
Le JORF nouveau est arrivé

### ISSUE THREAD

**Issue by martinkirch** [soulaklabs/bitoduc.fr#154]
Et il contient une traduction officielle (et tristement littérale) de "Dark Web"

https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000035638782&dateTexte=&categorieLien=id

Camarades esthètes taquins, voilà du pain sur la planche.

**Comment by maeligg** [comment]
"Abysse" pour le deep web est joliment imagé (à défaut d'être très clair).

**Comment by p0nce** [comment]
La sombre toile ?

**Comment by martinkirch** [comment]
Le bitoduc officiel à jour : http://www.culturecommunication.gouv.fr/content/download/169264/1885116/version/1/file/Vocabulaire-TIC_en%20ligne.pdf

**Comment by martinkirch** [comment]
Même l'ANSSI entre en concurrence
http://www.ssi.gouv.fr/administration/glossaire/

**Comment by martinkirch** [comment]
Personne ne s'attend à la COMMISSION D’ENRICHISSEMENT DE LA LANGUE FRANÇAISE 
https://www.legifrance.gouv.fr/jo_pdf.do?id=JORFTEXT000036449955

**Comment by martinkirch** [comment]
Quelque part entre Vendredi Noir et Noël https://www.legifrance.gouv.fr/jo_pdf.do?id=JORFTEXT000037769128

**Comment by p0nce** [comment]
L'Etat nous vole notre travail !
