### ISSUE TITLE
La traduction officielle de "blockchain" sera "dispositif d'enregistrement électronique partagé"

### ISSUE THREAD

**Issue by martinkirch** [soulaklabs/bitoduc.fr#155]
Source: https://www.lesechos.fr/finance-marches/gestion-actifs/030986376978-lordonnance-blockchain-a-ete-adoptee-en-conseil-des-ministres-2137022.php
Ce qui donne un acronyme, "DEEP", plus en rapport avec la ligne éditoriale du Dictionnaire Commun.

**Comment by p0nce** [comment]
le DEEP ou la DEEP?

**Comment by jusdepatate** [comment]
Ca dépend dans quoi :D 
pardon pour cette blague

**Comment by martinkirch** [comment]
mise à jour dans l'atome ccb8a59
