### ISSUE TITLE
Règles typographiques liées à la ponctuation

### ISSUE THREAD

**Issue by MonsieurPi** [soulaklabs/bitoduc.fr#160]
En français il y a une espace avant les deux-points. Dans le site vous ne mettez pas cette espace pour les traductions, ce qui fait un peu tâche. ;-P

**Comment by MonsieurPi** [comment]
Je peux le faire.

**Comment by jmazon** [comment]
ÀMHA ça ferait plus tache que tâche. Du moins jusqu'à la fusiodemande.

**Comment by MonsieurPi** [comment]
Pas compris. :joy:

**Comment by p0nce** [comment]
Il s'agissait de #165
