### ISSUE TITLE
Application mobile

### ISSUE THREAD

**Issue by PaulSec** [soulaklabs/bitoduc.fr#161]
Bonjour à tous, 

Suite à notre ping sur Twitter, j'aurais aimé savoir s'il était possible d'utiliser les traductions bitoduc dans une petite application mobile sans prétention :-) 

Bon week-end à tous,

**Comment by p0nce** [comment]
Décidé avec @martinkirch  mais je suis certain que le reste de l'équipe Bitoduc.fr acquiescera : **oui** bien sur ! Il serait louable que la marque "Bitoduc" soit conservée dans cette application pour malinphone.

Pour que cela soit plus clair pour l'ensemble de nos partenaires, nous allons résoudre #78.

**Comment by p0nce** [comment]
Tenez-nous au courant des bails.

**Comment by progval** [comment]
Des baux !
