### ISSUE TITLE
Pastebin ?

### ISSUE THREAD

**Issue by hydrargyrum** [soulaklabs/bitoduc.fr#177]
Que pensez vous de « _Dépôt de colles_ » (ou collages) ?

**Comment by maeligg** [comment]
+1 dépot de collages

**Comment by chmduquesne** [comment]
Je suggère collodrôme

**Comment by maeligg** [comment]
Sans accent circonflexe alors sinon on parle du département. ;)

**Comment by chmduquesne** [comment]
Ah oui 😊 Bon, mon excuse est que j'ai grandi en Provence, pas loin de la
Drôme.

**Comment by hydrargyrum** [comment]
À ne pas confondre avec le coulindrum.

**Comment by GuillaumeCailhe** [comment]
Sur le site, il y a l'accent circonflexe à collodrome.
Ca serait mieux de l'enlever comme dit plus haut.
