### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by Pimprebix** [soulaklabs/bitoduc.fr#180]
traduit par  "trace" ou "note"

**Comment by progval** [comment]
Historique

**Comment by chmduquesne** [comment]
Journal

**Comment by pjoubert-** [comment]
j'aime bien parler de bûche.
il semble que l'usage anglais vienne de la marine, où l'on tenait un logbook, la bûche permettant d'estimer la vitesse du vaisseau: https://en.wikipedia.org/wiki/Logbook

**Comment by chmduquesne** [comment]
J'aime bien, mais ne serait-ce pas un peu littéral?

Vous avez raison pour l'usage anglais: le logbook est l'endroit où l'on consigne la vitesse du bateau, obtenue à l'aide d'un [chip log](https://en.wikipedia.org/wiki/Chip_log). Si l'on suit votre logique jusqu'au bout, il faudrait alors utiliser la traduction française de cet instrument, qui n'est autre que le [Loch](https://fr.wikipedia.org/wiki/Loch_(bateau)).

J'ai quand même l'impression qu'au sens de l'informatique, les logs désignent plus le moyen de consigner les métriques que l'instrument de mesure. C'est pourquoi je pense que la traduction de ce mot par journal serait plus appropriée, car en français le logbook s'appelle le journal de bord.

**Comment by chmduquesne** [comment]
Ceci dit bûche c'est quand même bien dans l'esprit bitoduc.
