### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by Pimprebix** [soulaklabs/bitoduc.fr#181]
requete de tirage

**Comment by ghost** [comment]
Il est déjà traduit par « fusiodemande » sur bitoduc.fr (bloc de texte du haut) mais ne fait pas partie de la liste ; à ajouter :-)

**Comment by chmduquesne** [comment]
Déjà bien traduit

**Comment by alexisLefebvre** [comment]
_Fusiodemande_ n'apparaît pas dans la liste des traductions.

**Comment by progval** [comment]
En effet :O

**Comment by alexisLefebvre** [comment]
La traduction est bien dans le fichier:

https://github.com/soulaklabs/bitoduc.fr/blob/0f6959abd8c6a27a721eebcb646684003a2aa888/liste_de_traductions.json#L137

C'est le site http://bitoduc.fr/ qui ne doit pas être à jour
