### ISSUE TITLE
Octet /=/ Byte

### ISSUE THREAD

**Issue by bc1bb** [soulaklabs/bitoduc.fr#188]
Je suis pas sur mais il me semble

**Comment by p0nce** [comment]
Moi aussi il me semble, mais je ne suis pas sur.

**Comment by chmduquesne** [comment]
* https://en.wikipedia.org/wiki/Byte: "The byte is a unit of digital information that most commonly consists of eight bits [...]"
* https://fr.wikipedia.org/wiki/Octet: "En informatique, un octet est un multiplet de 8 bits codant une information [...]"
* https://fr.wikipedia.org/wiki/Byte: Le byte (prononcé /baɪt/), ou multiplet en français1, est, indépendamment de l'adressage physique de la mémoire, la plus petite unité « logiquement » adressable par un programme sur un ordinateur.

Je vois où vous voulez en venir: techniquement sur des ordinateurs d'avant 1970, on a eu des ordinateurs pouvant adresser des bytes de 4 bits et autres loufoqueries.

Cela fait presque 50 ans que ce type de matériel n'existe plus. De nos jours, aucun anglophone n'oserait plus parler de bytes qui ne feraient pas 8 bits. Le site bitoduc.fr a été créé pour pallier aux problèmes du français moderne, je suggère donc qu'il se réfère au matériel moderne, quitte à faire des raccourcis. N'oublions pas l'homme du peuple, et que l'esprit des lumières veille sur nous!

**Comment by bc1bb** [comment]
Ah ok, bon, ben je me tais x)
(J’ai une question aussi: vous avez un serveur Discord ou un logiciel du genre?)

**Comment by p0nce** [comment]
Cher ami,

Bienvenue sur ce temple de la sémantique, sur l'autel de la Gloire ; ici nous tricotons - jour après jour - nos propres habit verts.

Un octet, depuis l'Antiquité (bien avant la _synthwave_) est composé de 8 bits. **Il n'y a malheureusement pas à tortiller.**

Dans la Guerre des Gaules, _Caius Iulius Caesar_ écrit en 55 av. JC:
```
Sunt VIII bits scilicet una bitus est computare.
```
 Ce qui ne laisse guère de place à l'interprétation.

Quant à communiquer avec nous par Discord, nous n'avons que mépris intense pour celleux  qui voudraient rendre propriétaires nos conversations (renseignez-vous sur le modèle d'affaires de Discord !), et ainsi se repaître goulûment de nos confidences et données privées.

Cet humble répertoire de bogues est notre seul et unique moyen de communication et de collaboration, et je l'espère pour vous, verra s'épanouir une synergie fructueuse.
