### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by martinkirch** [soulaklabs/bitoduc.fr#195]
Salut les esthètes taquin·e·s,

Il manque une traduction de `deprecated`. Me viennent à l'esprit :

* désapprouvé·e
* déprécié·e 
* obsolète

Mais je ne sais trancher. A l'aide !

**Comment by quentin** [comment]
J'utilise toujours déprécié·e.

**Comment by chmduquesne** [comment]
Il n'y a, à mon sens, qu'une seule traduction qui tienne la route parmi les trois proposées, et c'est « obsolète ».
* « désapprouvé·e » signifie que l'objet en relation ne devrait pas être utilisé, mais ne transmet pas l'idée que ça a été différent dans le passé (ce qu'on veut on veut vraiment dire, c'est que l'objet en relation ne devrait _plus_ être utilisé)
* « déprécié·e » s'utilise dans le contexte d'une valeur monétaire (un titre ou une action peuvent se déprécier), ou dans le sens de dénigrer (déprécier quelqu'un). Pour moi c'est un faux ami régulièrement mal utilisé (un peu comme « assigner » est un terme de justice mal utilisé pour traduire « affecter »).

**Comment by quentin** [comment]
Ringardisé·e pourrait convenir.

**Comment by chmduquesne** [comment]
> Ringardisé·e pourrait convenir.

Formidable. Le côté obsolète est parfaitement transmis. L'avantage de cette traduction est qu'elle tient compte du fait que cette obsolescence a été "activée" par quelqu'un. Pour traduire "to deprecate", on serait obligé de dire "rendre obsolète", ce qui n'est pas tout à fait exact car en général quelque chose est rendu obsolète par l'apparition d'une autre chose et non par la décision de quelqu'un. Or, il est tout à fait possible de décider qu'il ne faut plus utiliser une fonction car on a décidé de ne tout simplement plus supporter celle-ci, sans pour autant offrir de remplacement pour celle-ci. À ce moment là, "rendre obsolète" peinerait à transmettre cette idée là où "ringardiser" continuerait à fournir une excellente traduction.

Je trouve que c'est une excellente proposition, en plein accord avec la ligne éditoriale du site.
