### ISSUE TITLE
A quoi bon l'attribut `pluriel` ?

### ISSUE THREAD

**Issue by martinkirch** [soulaklabs/bitoduc.fr#200]
Actuellement toutes les entrées ont un attribut `pluriel` qui, en plus d'être inutilisé, est systématiquement (et sans doute suite à une tradition de copier-coller) `false`. Sauf pour les feuilles de style en cascade, _comme par hasard_ https://github.com/soulaklabs/bitoduc.fr/blob/gh-pages/liste_de_traductions.json#L42

🎅 Je propose que nous retirions cet attribut 🎅

**Comment by martinkirch** [comment]
Quoi de mieux pour la 200è ? :tada:

**Comment by p0nce** [comment]
Ca donne l'impression qu'on a une direction. 💪

**Comment by martinkirch** [comment]
Résolu suite a la FD #203
