### ISSUE TITLE
Rollback ?

### ISSUE THREAD

**Issue by F0xtr0t-Sn0w** [soulaklabs/bitoduc.fr#212]
Qu'est-ce que cela pourrait devenir ? Peut-être existe-t-il une autre traduction que "retour en arrière"

**Comment by martinkirch** [comment]
Rétropédalage ?

**Comment by chmduquesne** [comment]
Rembobinage

**Comment by quentin** [comment]
J'aime beaucoup rétropédalage.

**Comment by p0nce** [comment]
Rembobinage est plus correct, non ? La correction, c'est important.

**Comment by quentin** [comment]
Rembobiner serait la traduction de "rewind".

**Comment by martinkirch** [comment]
Exactement, et surtout "rétropédalage" sous-entend l’échec alors que "rembobinage" colporte la nostalgie des requêtes réussies qu'on a envie de rejouer.

En SQL, invoquer _ROLLBACK_ c'est sonner la retraite : rétropédaler. Merci @F0xtr0t-Sn0w  d'avoir signalé ce manque à nos traductions !

**Comment by F0xtr0t-Sn0w** [comment]
De rien ! J'utilise Bitoduc assez régulièrement pour ne pas faire d'anglicisme au travail et je dois avouer qu'on rigole bien avec nos collègues quand d'autres essaient de nous "comprendre" 
Avec joie que je participe donc à l'enrichissement de cette encyclopédie
