### ISSUE TITLE
Séparer le code des données

### ISSUE THREAD

**Issue by chmduquesne** [soulaklabs/bitoduc.fr#25]
Pour l'instant, les traductions des mots sont dans le dictionnaire `vrais_mots`, directement dans le javascript du site. Afin de rendre les données plus faciles à utiliser par des tierces parties (ex: un automate qui corrigerait des tweets), il faudrait héberger les données à part. Le plus facile serait sans doute de mettre ce dictionnaire dans un fichier json à la racine du site.

**Comment by progval** [comment]
Note : ce n’est pas si difficile à analyser : https://github.com/ProgVal/Supybot-plugins/blob/da65ce58b453fc922829da69c4a7338bd1cd63eb/Bitoduc/plugin.py#L48-L64

**Comment by p0nce** [comment]
J'aime bien, ça introduit un couplage rigolo et c'est l'occasion d'avoir un peu de dette technique comme tous les plus grands sites.

**Comment by chmduquesne** [comment]
Donc il y a un plugin pour automate IRC qui s'interface avec bitoduc.fr?

Oh.
Mon.
Dieu.

**Comment by p0nce** [comment]
Sur quel canal peut-on parler à ce clavarbot @ProgVal ?

**Comment by progval** [comment]
#supybot-fr @ freenode
