### ISSUE TITLE
Semaphore -> Sémaphore

### ISSUE THREAD

**Issue by greg7mdp** [soulaklabs/bitoduc.fr#254]

**Comment by quentin** [comment]
Merci pour cette suggestion. Cependant elle ne répond à la portée antiencyclopédique du Bitoduc.
N'hésitez pas à faire d'autres propositions.

**Comment by p0nce** [comment]
Merci pour cette proposition, cependant elle est tout à fait inacceptable en l'état (pour des raisons évidentes).
