### ISSUE TITLE
Just-In-Time, Juste-À-Temps, On The Fly, À La Volée, Sur La Mouche

### ISSUE THREAD

**Issue by quentin** [soulaklabs/bitoduc.fr#263]
Nous avons actuellement "Compilateur à la volée" pour "JIT Compiler".

Mais une meilleure interprétation de "Just-In-Time" serait "Juste-À-Temps". Et "À La Volée" correspond à "On The Fly" (Sur La Mouche).

**Comment by p0nce** [comment]
Et pourquoi pas "à la demande"?

**Comment by quentin** [comment]
> Et pourquoi pas "à la demande"?

Comment traduirions-nous les nombreux _Some Bullshit-On-Demand_ ?
