### ISSUE TITLE
La forme "grand boutien", "petit boutien" est peu correcte et perd la référence aux Voyages de Gulliver. 

### ISSUE THREAD

**Issue by wazoox** [soulaklabs/bitoduc.fr#266]
En effet, la nominalisation de "bout" est normalement "boutiste": jusqu'au-boutiste.
Dans les Voyages de Gulliver, deux peuplades se font la guerre sur la question de par quel côté on doit entamer les œufs à la coque: par le petit ou par le gros bout? C'est la référence derrière "gros-boutiste" (ou gros-boutien) et "petit-boutiste". Ces termes sont utilisés depuis plusieurs décennies (présents dès les plus anciennes versions du jargon français). De plus, rien n'est plus français et élégant qu'une obscure référence littéraire.
Tant qu'à être snobs et à utiliser des termes français, autant aller jusqu'au bout de la démarche (scrogneugneu et saperlipopette).

**Comment by quentin** [comment]
Très intéressant, iriez-vous jusqu'au bout de la démarche en proposant une fusiodemande ?

**Comment by wazoox** [comment]
Je vais essayer :)

**Comment by quentin** [comment]
C'est fait, grand merci.
