### ISSUE TITLE
Obfuscation -> Caviardage de code (en lieu et place de "Noircissement de code")

### ISSUE THREAD

**Issue by abidon** [soulaklabs/bitoduc.fr#273]
Bonjour,

Dans la veine des grands noms de la tech qui retirent les mots maître et esclave de leurs documentations techniques, je propose de remplacer le terme Noircissement en [Caviardage](https://fr.wiktionary.org/wiki/caviarder#fr)

Cordialement

**Comment by FazCodeFR** [comment]
Bonjour,
moi aussi je rajoute : 
CRYPTOGRAPHIE
Tout est expliqué ici :  https://chiffrer.info/
