### ISSUE TITLE
shell ?

### ISSUE THREAD

**Issue by progval** [soulaklabs/bitoduc.fr#29]
« Coquille », en se basant sur la traduction « code encoquillé » de « shell code » ?

**Comment by p0nce** [comment]
Si l'on revient aux principes d'UNIX, le "shell" est une sorte d'établi, de lieu de travail depuis lequel pourront être appelés différents outils. Un programme de possibilités multiples auquel on accède en premier.

Ce n'est pas une boite à outil cependant, qui est un concept fermé (les outils ne sont pas _dans_ la boite), mais ouvert : un lien symbolique va rajouter tel ou tel programme dans notre vocabulaire. Dans ce sens je ne suis pas sur que « coquille » fasse honneur à cet esprit-là.

C'est donc une sorte de table lexicale, dotée qui plus est d'un langage, mélange hasardeux et pastiches d'autres langages textuels faiseurs de "shell scripts". Enfin le "shell" est une session, qui correspond à une transaction entre l'utilisateur et la machine, et qui à donc une durée tout à fait limitée.

Quel mot pourrait nous satisfaire ?

**Comment by emillon** [comment]
Je propose « interprète de commandes ». Un mot unique serait le bienvenu mais l'inspiration me manque. (EDIT: chevrons)

**Comment by p0nce** [comment]
Riche idée.

**Comment by progval** [comment]
« établi » me semble être une bonne idée. Mais ce n’est pas très intuitif.
