### ISSUE TITLE
update "DDOS" and "DOS" based on legifrance

### ISSUE THREAD

**Issue by toob** [soulaklabs/bitoduc.fr#302]
cf. https://www.legifrance.gouv.fr/download/pdf?id=rlq0ST1P-m5DOunYLkEQQYe11ylHyGVe0DFbiO6xpuw=

**Comment by martinkirch** [comment]
Malgré toute notre reconnaissance envers nos camarades de la commission d'enrichissement de la langue française, il est clair que cette édition du 19 Mars est hélas moins inspirée que d'habitude et diverge de l'esprit du site :/
