### ISSUE TITLE
Genre des noms

### ISSUE THREAD

**Issue by progval** [soulaklabs/bitoduc.fr#31]
Il pourrait être utile d’avoir un moyen d’indiquer le genre des noms. Par exemple, tout le monde ne genre pas intuitivement « bogue » de la même façon.

**Comment by p0nce** [comment]
Bonne idée. A rajouter dans les tables de mots.

**Comment by chmduquesne** [comment]
Excellente idée. Si quelqu'un me fait une PR avec un fichier à jour sur les genres, je veux bien modifier le javascript pour afficher "NF" ou "NM" à l'endroit approprié.

**Comment by progval** [comment]
Problème : il n’y a pas que des noms/groupes nominaux. Et tous ne sont
pas au singulier.

**Comment by chmduquesne** [comment]
Hum. Dans ce cas je peux n'utiliser la clé genre que si elle est présente.

2015-12-07 14:27 GMT+01:00 Valentin Lorentz notifications@github.com:

**Comment by p0nce** [comment]
Fait par @ProgVal
