### ISSUE TITLE
Gestion de l'attente des contributeurs

### ISSUE THREAD

**Issue by chmduquesne** [soulaklabs/bitoduc.fr#41]
Il faudrait bien expliquer quelque part la ligne éditoriale de ce site, afin de ne pas décevoir les gens qui proposent des traductions officielles alors que le site fait des choix différents.

Il y a clairement une dimension humoristique, mais les traductions se veulent pertinentes. Il faudrait le préciser pour que les contributeurs comprennent les refus de leur fusiodemandes.

**Comment by progval** [comment]
GitHub prend en compte l’existence d’un fichier `CONTRIBUTING.md` pour l’indiquer aux personnes contribuant lorsqu’elles ouvrent un ticket ou une fusiodemande.
Ça pourrait être un bon endroit où mettre ces indications.

**Comment by p0nce** [comment]
Bon point.

**Comment by p0nce** [comment]
Après moult discussions, nous avons ceci: https://github.com/soulaklabs/bitoduc.fr/blob/gh-pages/CONTRIBUER.md

**Comment by chmduquesne** [comment]
Je considère donc ce problème comme réparé.
