### ISSUE TITLE
wildcard et placeholder ?

### ISSUE THREAD

**Issue by progval** [soulaklabs/bitoduc.fr#42]
wildcard : joker ? carte sauvage ? caractère générique ? meilleur deuxième (référence au contexte sportif) ? Métacaractère ?
placeholder : preneur de place ? Lorem ipsum ? Faux-texte ?

**Comment by chmduquesne** [comment]
Pour moi, « Wildcard » se traduit clairement par « Joker », et vice versa.
Je n'ai pas de suggestion pour « Place holder ».

**Comment by p0nce** [comment]
+1 pour "Wildcard" = « Joker »

Pour "placeholder": un simulacre ?

**Comment by chmduquesne** [comment]
Pour placeholder, je trouve que wikipedia a raison et que la traduction
dépend du contexte : https://fr.wikipedia.org/wiki/Marque_substitutive

**Comment by p0nce** [comment]
C'est bien « Marque substitutive ».

**Comment by chmduquesne** [comment]
Je trouve aussi.

**Comment by p0nce** [comment]
Alea jacta est.
