### ISSUE TITLE
Bitoduc grandit, faut-il créer une organisation Github?

### ISSUE THREAD

**Issue by p0nce** [soulaklabs/bitoduc.fr#52]
Quand `bitoduc.fr` est dans un gazouillis, par exemple dans https://twitter.com/xme/status/673503877401022464, ça affiche mon image de profil.

Mais je ne suis plus un contributeur essentiel à la perennité. Je propose donc créer une organisation Github, où les contributeurs actuels auront les même pouvoirs, afin de me sortir de l'addresse réticulaire.

Vos avis ?

**Comment by chmduquesne** [comment]
Je trouve que c'est une bonne idée, oui!

Je ferais bien une organisation nommée soulaklabs pour y mettre aussi
tofbot.

2015-12-07 0:21 GMT+01:00 Guillaume Piolat notifications@github.com:

**Comment by p0nce** [comment]
Ah ouais grave!

**Comment by p0nce** [comment]
Merci @chmduquesne
