### ISSUE TITLE
La classe grammaticale de "Petit boutien" et "Intrusé"

### ISSUE THREAD

**Issue by p0nce** [soulaklabs/bitoduc.fr#58]
Quelle est-t'elle ?

**Comment by progval** [comment]
adjectif ?
Et ne serait-ce pas plutôt « petit-boutien » ?

**Comment by emillon** [comment]
Petit boutien est un adjectif [(wiktionary)](https://fr.wiktionary.org/wiki/grand-boutiste). Intrusé de même.
