### ISSUE TITLE
Newsletter <-> Infolettre ?

### ISSUE THREAD

**Issue by p0nce** [soulaklabs/bitoduc.fr#63]
Source: Concours Francomot 2010

**Comment by p0nce** [comment]
Ainsi que "buzz" <-> "ramdam"

**Comment by progval** [comment]
:+1: pour les deux

**Comment by progval** [comment]
Penser à mettre à jour « buzzword », aussi.

**Comment by p0nce** [comment]
Mettre à jour en quoi ?

**Comment by p0nce** [comment]
aa6a999c5ac2818ae8d59a7de4edb1925051a7d3
