### ISSUE TITLE
Smart grids

### ISSUE THREAD

**Issue by chmduquesne** [soulaklabs/bitoduc.fr#73]
Traduit par grilles malignes. Ce ne devrait pas plutôt être grilles malines?

**Comment by progval** [comment]
Non. cf #45

**Comment by progval** [comment]
et aussi : https://fr.wiktionary.org/wiki/maline#Forme_d.E2.80.99adjectif

**Comment by chmduquesne** [comment]
ATPM

**Comment by progval** [comment]
« ATPM » ?

**Comment by chmduquesne** [comment]
[ATPM](https://fr.wiktionary.org/wiki/au_temps_pour_moi) :)
