### ISSUE TITLE
En-têtes de droits d'auteurs dans le code

### ISSUE THREAD

**Issue by chmduquesne** [soulaklabs/bitoduc.fr#77]
Il faudrait qu'on les ajoute, ce serait pédant. Comment fait-on, en français?

**Comment by progval** [comment]
https://fr.wikipedia.org/wiki/WTFPL#Traduction_fran.C3.A7aise_officielle_de_la_version_2 ?

**Comment by progval** [comment]
ou http://www.cecill.info/ ?

**Comment by chmduquesne** [comment]
Ne confondons pas droits d'auteur et licence. Je parle de:

```
Copyright (C) 2009 Sam Hocevar
```

Il nous faudra aussi une licence, et je suis pour ma part aussi en faveur de la WTFPL, mais je parle bien des droits d'auteur.

**Comment by p0nce** [comment]
La WTFPL n'est il me semble pas reconnue partout, alors qu'UNLICENSE oui.
Être impertinent oui, mais dans le respect de la Loi et de son esprit.

Je vote pour la license CeCILL, qui me semble tout indiquée.

**Comment by chmduquesne** [comment]
Faisons un autre sujet pour la licence.

**Comment by chmduquesne** [comment]
La licence est dans #78. Nous parlons ici des en-têtes de droits d'auteurs.

**Comment by chmduquesne** [comment]
J'ai tiré toutes les informations de git log, qui sont publiques. J'en ai déduit qu'il était acceptable de mettre les adresses de chacun. Vous pouvez à souhait apporter les modifications qui vous paraîtrons oportunes.
