### ISSUE TITLE
*-like

### ISSUE THREAD

**Issue by progval** [soulaklabs/bitoduc.fr#86]
On me demande une traduction pour « bytes-like », où « bytes » est le nom d’un type et ne devrait donc pas être traduit.
Que suggérez-vous pour ce genre cas ?

**Comment by p0nce** [comment]
Un simili-bytes ?
Un quasi-bytes ?
Un tout-comme-bytes ?

**Comment by progval** [comment]
« simili-* » me plait

**Comment by JulienPalard** [comment]
"simili-*" me plaît pas mal, de mon côté (je suis à l'origine de la question, le "On" dans la question de @ProgVal) j'utilise pour le moment "bytes-compatible", sémantiquement très juste, peut être un poil plus juste que simili, mais tout comme "simili", le mélange "français-anglais" me gêne et me pousse à carrément laisser "bytes-like", qui me déplaît aussi.

Dans mon contexte ([traduction de la documentation de Python](http://www.afpy.org/doc/python/3.5/glossary.html)), comme le disais @ProgVal, je ne peux pas traduire _bytes_ puisque c'est un type de Python (je traduis la doc, pas le code, _bytes_ est donc pour moi dans ce contexte, peut être un nom propre ?).

Ne pas traduire "bytes-like" reviens à considérer "bytes-like" comme "bytes", un genre de nom propre, ce qui est faux, aussi, ça désigne un ensemble, pas une entité.

Après, on entend souvent "quake-like" dans des articles en français, ça ne m'autorise pas pour autant à l'utiliser, mais au moins je me dis que les gens comprendront probablement.

**Comment by JulienPalard** [comment]
Tiens, dans le contexte, "Des objets bytes-compatibles" passe mieux que "Des objets simili-bytes".

**Comment by p0nce** [comment]
Dans ce contexte, on pourrait dire aussi des objets « compatibles avec bytes ».

Pour le cas "quake-like" on pourra tout simplement parler de « clone de Quake ». C'est sémantiquement différent, pas fantastique mais il me semble qu'il y a un précédent.

Il est vrai que nous n'avons pas de solution définitive pour le moment, et encore moins pour les deux cas.

**Comment by emillon** [comment]
Il me semble que "X-compatible" est un anglicisme donc plutôt à éviter.

La construction "simili-X" a le bon goût d'être déjà existante dans le vocabulaire non technique, comme dans "simili-cuir", mais a une connotation "aspect". Le suffixe "-forme" désigne la même idée mais avec une connotation "forme" (bien entendu): "cunéiforme" (en forme de coin), "sphéroforme" (en forme de sphère),etc. La version grecque est "-morphe" comme dans "anthropomorphe".

On peut imaginer un "bytes-forme" ou "bytes-morphe" mais étant donné que la racine ne peut être traduite, le mot résultant aura toujours un aspect rafistolé. L'anglais et l'allemand se prêtent bien à cet exercice, le français un peu moins à mon avis.

J'irais vers un "compatible avec bytes" ou "simili-bytes".

**Comment by progval** [comment]
> La construction "simili-X" a le bon goût d'être déjà existante dans le vocabulaire non technique, comme dans "simili-cuir", mais a une connotation "aspect"

C’est justement le but recherché, non ?

**Comment by emillon** [comment]
Oui, c'est pour ça qu'il retient mon intérêt. Je pensais que cela s'arrêtait à l'aspect physique d'où ma remarque, mais en fait [c'est la notion d'imitation qui est importante](http://www.cnrtl.fr/definition/academie8/simili). C'est donc la bonne traduction.

**Comment by p0nce** [comment]
Malgré l'adéquation de ce préfixe « simili- » à la situation (je crois que nous avons un gagnant !), il est bon de faire un rappel comme le dit justement @emillon. 
Créer des mots composés « à la volée » est un anglicisme/germanisme avec une moustache, et nous sommes souvent tombés dans le panneau. 
Restons vigilants, pour notre sécurité à tous.

**Comment by progval** [comment]
> un anglicisme/germanisme avec une moustache

Pardon ?

**Comment by p0nce** [comment]
« Avec une moustache » au sens de « déguisé ».

**Comment by p0nce** [comment]
Par exemple:

```
Le "machine learning" c'est les statistiques avec une moustache.
```

**Comment by JulienPalard** [comment]
Je pense aussi que "simili-" est un gagnant, cependant je pense qu'il faut qu'on attende de tomber sur un cas réel pour le valider, je serai d'avis, pour mon cas particulier où le 2ème mot de mon mot composé doit rester en anglais, de garder le suffixe "-like". Si ça ne vous paraît pas déconnant.

Mais on pourrait aussi considérer "byte" ici comme le nom propre du type en Python (ce qui est vrai), ce qui nous autorise (je pense) à le mélanger à du français (rien ne semble incohérent dans l'usage de prénoms anglais dans un texte français, parlons d'Alan Turing en Français).

En ce cas j'aurais dans mon cas:
- binary file: A file object able to read and write bytes-like objects.
  - fichier binaire: Un objet fichier capable de lire et d'écrire des objets simili-bytes.
- Bytes-like objects can be used for various operations...
  - Les objets simili-bytes peuvent être utilisés dans diverses opérations...
- File objects are also called file-like objects or streams
  - Les objets fichier sont aussi nommés objets simili-fichier ou _streams_

C'est encore un poil dissonant à mon oreille.

**Comment by progval** [comment]
« flux », comme traduction pour « stream »

**Comment by chmduquesne** [comment]
Fermé car vieux/Pas assez spécifique à l'informatique.
