### ISSUE TITLE
Traduction de "noob"

### ISSUE THREAD

**Issue by conchyliculture** [soulaklabs/bitoduc.fr#90]
Vu qu'on parle de "navigation" sur l'Internet, je propose "mousse".
Autre possibilités:
"Béjaune", contraction de "bec jaune" peut s'appliquer également sur une plaforme de gazouillage.

Pour rester plus proche lexicographicalement, pourquoi pas contracter "Novice" en "Nove".

Une autre possibilité serait le court mais ambigü "Bleu".

**Comment by p0nce** [comment]
Je vote "Bleu".

**Comment by progval** [comment]
Je vote Novice/Nove, que je trouve plus joli.

En plus, c’est appréciable d’avoir un substantif/adjectif sans marque de genre, c’est plus pratique quand on ne connait pas le genre de la personne concernée (par exemple quand on traduit de l’anglais).
