### ISSUE TITLE
Quand soudain: un mot de création française

### ISSUE THREAD

**Issue by martinkirch** [soulaklabs/bitoduc.fr#91]
"illectronisme", in http://www.assemblee-nationale.fr/14/amendements/3399/AN/203.asp

mais que faire ?!

**Comment by chmduquesne** [comment]
"Software illiterate"

**Comment by p0nce** [comment]
"Computer illiterate"

**Comment by chmduquesne** [comment]
Computer illiteracy

**Comment by martinkirch** [comment]
Besoin de références.

**Comment by chmduquesne** [comment]
Fermé par la contribution de @ProgVal
