### ISSUE TITLE
Capitalization = mise en capitales

### ISSUE THREAD

**Issue by pierreporte** [soulaklabs/bitoduc.fr#95]
Tout d’abord, il faut savoir que les majuscules et les capitales sont deux choses différentes. Les majuscules sont toujours des capitales mais l’inverse n’est pas vrai. Quand un nom propre est mis en capitale, il y a toujours le même nombre de majuscules. Par exemple, dans « NICOLAS SARKOZY », il y a quatorze capitales dont deux majuscules.

Ensuite, « majusculation » n’est pas agréable à lire et à prononcer. En prenant en compte le premier point, si on choisissait « capitalation » (pour ne pas créer un homonyme de « capitalisation »), le problème persiste bien qu’à mon sens le mot soit plus agréable.

Enfin, on peut tout à fait exprimer le mot sans créer de néologisme de manière très simple pour seulement quatre lettres de plus que « capitalation » et deux de plus que « majusculation ». Je crois également qu’on a pas affaire ici à un mot particulièrement usité.

**Comment by ProgVal** [comment]
Du coup, comment dit-on « capitalisation » en anglais ?

**Comment by progval** [comment]
Je n’ai pas bien compris en quoi « capitalisation » ne convienrait pas

**Comment by pierreporte** [comment]
« Capitalisation » conviendrait tout à fait s’il n’existait pas déjà un homonyme. De plus, « mise en capitales » est déjà utilisé par les typographes pour dire exactement la même chose que ce dont il s’agit ici.

Si on part de l’anglais où « capitalization » vient du verbe « to capitalize », alors on aurait aussi les verbes « majusculer » (particulièrement horrible à mon sens) et « capitaliser » (qui existe déjà pour exprimer une tout autre idée). À mon sens, dire « _capitaliser_ un mot » (par exemple) est moins clair que « _mettre en capitales_ un mot ». Il faut aussi penser aux personnes qui ne connaissent pas le sens de « capitalisation » comme « mise en capitales ».

En fait, c’est moi qui n’ai pas bien compris en quoi il vaut mieux créer un néologisme alors qu’on peut dire la même chose avec des mots qui existent déjà et avec une formule à peine plus longue que le nouveau mot.

**Comment by progval** [comment]
D’accord, j’ignorais que « mise en capitale » était déjà utilisé. Ça me semble bien, du coup.

**Comment by pierreporte** [comment]
C’est accepté, donc. Je vais faire une pull-request (ma première !)

**Comment by progval** [comment]
Une fusiodemande *

**Comment by pierreporte** [comment]
Demande de fusion *

**Comment by chmduquesne** [comment]
Le verbe marjusculer n'est pas sorti du chapeau, il existe véritablement:
https://fr.wiktionary.org/wiki/majusculer. Il signifie exactement la même
chose qu'en anglais, à savoir mettre une majuscule au début d'un mot:
http://www.merriam-webster.com/dictionary/capitalize. Ce n'est pas parce
que vous n'aimez pas le verbe qu'il n'en est pas moins valide. Je vote pour
le garder tel quel.

**Comment by chmduquesne** [comment]
Pour illustrer le caractère légitime du verbe, outre les références à Fernand Deligny et au Contrat Social que nous trouvons sur wiktionary.com, nous pouvons citer [Prévert](http://classes.bnf.fr/ecrirelaville/textes/05_3.htm) dans son poème de 1946 _Tentative de description d'un dîner de têtes à Paris-France_

> Ceux qui majusculent
> Ceux qui chantent en mesure

Pourquoi se priver d'une traduction qui est exacte et correcte?

**Comment by chmduquesne** [comment]
Pour finir, « mise en capitales » serait une traduction incorrecte de « capitalization », puisque cette traduction sous entend que toutes les lettres du mot sont écrites en capitales. Ce n'est pas le sens du verbe anglais, qui ne réfère qu'à la première lettre. Lorsqu'on souhaite le faire pour toute les lettres du mot, on parle plutôt d'écrire le mot en « [upper case](http://english.stackexchange.com/a/15914) ».

**Comment by p0nce** [comment]
Cher amis, faisons bon usage de ce ticket.
Nous avons là deux termes, et deux sens associés.
"put in upper case" pour la « mise en capitales »
Et « majusculation » qui ne fait pas si mal.

**Comment by chmduquesne** [comment]
J'approuve cette suggestion.

**Comment by pierreporte** [comment]
Je n’explique pas comment j’ai pu passer à côté de l’existence de « majusculer ».

Du reste, si le verbe « to capitalize » a bien le sens de « majusculer », il a aussi le sens de « mettre en capitales ». [La définition pointée](http://www.merriam-webster.com/dictionary/capitalize) par @chmduquesne atteste d’ailleurs des deux acceptations : « to write or print with an initial capital _or in capitals_ ».

D’autres dictionnaires anglais indiquent aussi que « to capitalise » a bien deux sens dans le contexte dont on discute ici :
- [Oxford Learner’s](http://www.oxfordlearnersdictionaries.com/definition/english/capitalize) : « capitalize something to write or print a letter of the alphabet as a capital; to begin a word with a capital letter ».
- [Collins](http://www.collinsdictionary.com/dictionary/english/capitalize) : « to write or print (text) in capital letters or with the first letter of (a word or words) in capital letters ».
- [Oxford](http://www.oxforddictionaries.com/fr/definition/anglais/capitalize) : « write or print (a word or letter) in capital letters » puis, plus loin, « begin (a word) with a capital letter ».
- [Cambridge](http://dictionary.cambridge.org/dictionary/english/capitalize) : « to write a ​letter of the ​alphabet as a ​capital, or to write the first ​letter of a word as a ​capital ».

Lorsqu’il est question d’une lettre « a letter », c’est « a » qui est utilisé et non « one », donc le pluriel est accepté.

J’admets avoir en partie tort mais il faudrait selon moi distinguer les deux acceptations du terme, quitte à indiquer laquelle est la plus courante en l’absence de contexte.

**Comment by chmduquesne** [comment]
La plupart des langages de programmation (tous?) qui disposent d'une fonction "capitalize" s'en servent dans le sens d'une mise en capitale de la première lettre. Exemples:
- [python](https://docs.python.org/2/library/stdtypes.html#str.capitalize)
- [ruby](http://ruby-doc.org/core-2.2.0/String.html#method-i-capitalize)
- [java](http://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/text/WordUtils.html#capitalize%28java.lang.String%29)
- [D](https://dlang.org/library/std/string/capitalize.html)

La personne cherchant sur bitoduc.fr l'équivalent français du nom de sa fonction veut une traduction rapide et précise. Vouloir lister toutes les acceptations du terme, c'est de la sodomie de brachycères. Pourquoi alors ne pas aussi traduire "capitalize" au sens de « capitaliser » (accumuler de manière à former un capital), puisque l'anglais accepte aussi cet usage?

**Comment by p0nce** [comment]
@chmduquesne : attention, les noms de ces langages doivent justement être capitalisés. On parlera de « Java » et non pas de "java".

**Comment by chmduquesne** [comment]
@ponce : Certainement, pardon.

@pierreporte : En fait, nous faisons face à une limitation voulue du site: les soumissions doivent comporter uniquement deux mots ou groupes de mots, l'un étant la traduction de l'autre et vice-versa. Plusieurs traductions pour le même mot ne sont pas possible, et nous souhaitons que cela reste comme ça.
