### ISSUE TITLE
« Fusio-demande » => « Demande de fusion » ?

### ISSUE THREAD

**Issue by p0nce** [soulaklabs/bitoduc.fr#97]
Depuis nos humbles débuts dans la nimposphère, nous avons choisi « fusio-demande » comme équivalent pour le bien connu "pull-request". Comme l'a fait remarquer @pierreporte, c'est peut-être une facilité.

Aurait-on fait un usage trop intensif de notre liberté de composer des mots? J'en appelle à votre jugement.

**Comment by chmduquesne** [comment]
Que l'on me qualifie de conservateur si l'on veut, mais je trouve que le néologisme « fusio-demande » est l'une des meilleures inventions de bitoduc.fr. Bien entendu, ce mot est incorrect et il faudrait employer « demande de fusion ». J'espère toutefois que l'élégance de la composition vous convaincra de garder cette traduction et de promouvoir son usage dans le langage courant.

**Comment by chmduquesne** [comment]
Je tiens à préciser que je ne suis pas "l'auteur" de ce mot. Mais je l'aime bien.

**Comment by p0nce** [comment]
C'est d'accord. Je ne m'attendais pas à un tel engouement.

**Comment by chmduquesne** [comment]
Laissons le débat ouvert encore un peu. Je ne suis peut-être pas le seul à avoir une opinion sur la question.

**Comment by progval** [comment]
Comme @chmduquesne, je trouve « fusiodemande » élégant et je suis en faveur de le conserver

**Comment by pierreporte** [comment]
Quitte à fusionner deux mots, pourquoi pas « requintégration » ? (« Requête » est un synonyme de « demande » et « intégration » de « demande » d’après le CNRTL.) Avec « requintégration », on peut former le verbe « requintégrer » (« je requintègre mon atome de code »).

Bien entendu, j’ai une préférence pour « demande de fusion » ou « demande d’intégration », « requête d’intégration », « requête de fusion », etc.

**Comment by p0nce** [comment]
Par deux votes contre deux, je déclare l'indécision gagnante de ce débat.
