### ISSUE TITLE
smiley

### ISSUE THREAD

**Issue by progval** [soulaklabs/bitoduc.fr#99]
Pas de traduction pour le moment, c’est volontaire ?

**Comment by chmduquesne** [comment]
Pas que je sache. Donne t'en à cœur joie :-)

**Comment by progval** [comment]
J’ai vu « souriard » et « frimousse », mais aucune des deux ne me plait

**Comment by p0nce** [comment]
« Émoticône » ?

**Comment by chmduquesne** [comment]
Nous avons #99 problèmes, et smiley en est toujours un.

**Comment by p0nce** [comment]
C'est résolu.
